export const seouls = [
  { value: "Jongno", name: "종로구" },
  { value: "Junggu", name: "중구" },
  { value: "Yongsan", name: "용산구" },
  { value: "Seongdong", name: "성동구" },
  { value: "Gwangjin", name: "광진구" },
  { value: "Dongdaemun", name: "동대문구" },
  { value: "Jungrang", name: "중랑구" },
  { value: "Seongbuk", name: "성북구" },
  { value: "Gangbuk", name: "강북구" },
  { value: "Dobong", name: "도봉구" },
  { value: "Nowon", name: "노원구" },
  { value: "Eunpyeong", name: "은평구" },
  { value: "Seodaemun", name: "서대문구" },
  { value: "Mapo", name: "마포구" },
  { value: "Yangcheon", name: "양천구" },
  { value: "Gangseo", name: "강서구" },
  { value: "Guro", name: "구로구" },
  { value: "Geumcheon", name: "금천구" },
  { value: "Yeongdeungpo", name: "영등포구" },
  { value: "Dongjak", name: "동작구" },
  { value: "Gwanak", name: "관악구" },
  { value: "Seocho", name: "서초구" },
  { value: "Gangnam", name: "강남구" },
  { value: "Songpa", name: "송파구" },
  { value: "Gangdong", name: "강동구" },
];
